### ISSUE TITLE
app运行不起来

### ISSUE THREAD

**Issue by Vicent9920** [AnyLifeZLB/MVP-Dagger2-Rxjava2#16]
OauthActivity的GravView报错：
`FATAL EXCEPTION: main
                                                                      Process: com.zenglb.framework, PID: 17203
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zenglb.framework/com.zenglb.framework.activity.access.OauthActivity}: android.view.InflateException: Binary XML file line #141: Error inflating class com.github.glomadrian.grav.GravView
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2304)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2354)
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:143)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5356)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: android.view.InflateException: Binary XML file line #141: Error inflating class com.github.glomadrian.grav.GravView
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:775)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:512)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:409)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:358)
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                          at com.zenglb.baselib.base.BaseActivity.onCreate(BaseActivity.java:31)
                                                                          at com.zenglb.framework.activity.access.OauthActivity.onCreate(OauthActivity.java:53)
                                                                          at android.app.Activity.performCreate(Activity.java:5301)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2268)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2354) 
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:143) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5356) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                          at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:614)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                          at com.zenglb.baselib.base.BaseActivity.onCreate(BaseActivity.java:31) 
                                                                          at com.zenglb.framework.activity.access.OauthActivity.onCreate(OauthActivity.java:53) 
                                                                          at android.app.Activity.performCreate(Activity.java:5301) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2268) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2354) 
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:143) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5356) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: java.lang.NullPointerException
                                                                          at com.github.glomadrian.grav.GravView.a(GravView.java:2037)
                                                                          at com.github.glomadrian.grav.GravView.<init>(GravView.java:39)
                                                                          at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                          at com.zenglb.baselib.base.BaseActivity.onCreate(BaseActivity.java:31) 
                                                                          at com.zenglb.framework.activity.access.OauthActivity.onCreate(OauthActivity.java:53) 
                                                                          at android.app.Activity.performCreate(Activity.java:5301) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2268) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2354) 
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:143) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5356) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                          at dalvik.system.NativeStart.main(Native Method) `
但是AS可以预览？怎么回事？

**Comment by AnyLifeZLB** [comment]
@Vicent9920 XML中注释掉
